#!/bin/bash
#kubectl uses OAuth token generated by
#gcloud config config-helper --format='value(credential.access_token)'
CLUSTER=`kubectl config current-context`
GCS_OAUTH_TOKEN=`kubectl config view -o json | jq --arg CLUSTER "$CLUSTER" '.users[]| select(.name==$CLUSTER)' | jq '.user."auth-provider".config."access-token"'`

echo "Token: $GCS_OAUTH_TOKEN"
echo ""
curl -s -S https://www.googleapis.com/oauth2/v1/tokeninfo\?access_token\="$GCS_OAUTH_TOKEN"

